### ISSUE TITLE
Příprava databázového modelu

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#1]
Připravit databázový model e-shopu v programu draw.io. Databázový model bude obsahovat jednotlivé tabulky a vazby mezi tabulkami.

Databázový model musí být exportován:
1. ve formátu **dbmodel.pdf** na sdíleném disku
2. ve formátu **dbmodel.drawio** na GitHubu

**Comment by matous-picl** [comment]
![Snímek obrazovky 2022-05-02 100537](https://user-images.githubusercontent.com/102512396/166203786-341dfbd9-04c4-4244-9d2e-32069d6c593b.png)

**Comment by matous-picl** [comment]
![Snímek obrazovky 2022-05-02 100537](https://user-images.githubusercontent.com/102512396/166207948-f4521c12-119d-4727-803f-50b14dfa89e4.png)

**Comment by kubaran11** [comment]
@matous-picl card_code je myšleno ten tříčiselný kód na zadní straně karty? Nevím jestli je dobrý nápad ho ukládat do databáze. Ale je pravda, že třeba Alza si ho asi ukládá, ale možná jenom, protože jsem jí to někdy povolil.

**Comment by kubaran11** [comment]
@matous-picl Perfektní práce!
