### ISSUE TITLE
Grafický návrh hlavní části webu

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#15]
Dle #11 a #13 připravit grafický návrh hlavní části webu.

**Prerekvizity**:

- [ ] #11
- [ ] #13

**Comment by davikra11** [comment]
![návrh školního webu](https://user-images.githubusercontent.com/102156616/166225795-6d5d73ba-6354-48ac-9bf1-5d548f53e02e.png)

**Comment by TomRehy** [comment]
barvy - černá #000000
             modrá #2E3192
             bílá #FFFFFF

**Comment by kubaran11** [comment]
@davikra11 Přidat na společný disk do zdrojových souborů.
