### ISSUE TITLE
Grafický návrh boxu s produkty

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#16]
Je nutné vytvořit grafický návrh interaktivního boxu s produkty, který bude obsahovat produkty dle filtrace.

**Prerekvizity**:

- [x] #17

**Comment by TomRehy** [comment]
![box produktu](https://user-images.githubusercontent.com/102223154/166424473-3e74c77f-36a2-4488-bd9f-41da7b6f61f3.png)

**Comment by TomRehy** [comment]
Když se najede na produkt kurzorem myši - zobrazí se další fotka produktu (například zadní část trička) a cena
