### ISSUE TITLE
Informace, které budou nutné u boxu s produkty

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#17]
Sepsat informace, které bude obsahovat každý produkt na stránce s výběrem produktů.

Příklad: Máme stránku, na které se ukáže například 12 produktů na jedné stránce. Jaké všechny vychytávky budou u daného produktu? Je nutné reflektovat, případně pozměnit #1, pokud by se informace musely ukládat do DB.

Výsledek: Do komentáře sem v issue.

**Comment by TomRehy** [comment]
fotka produktu - název, cena - když se najede na produkt - zobrazí se druhá varianta fotky (například zadní část trika/mikiny)
