### ISSUE TITLE
Obsah stránky s jedním produktem

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#18]
Seznam informací a funkcionalit, co bude obsahovat stránka s jedním konkrétním produktem (šablona pro všechny produkty). Zamyslet se i nad přidáním zboží do košíku.

Výsledek: V komentáři k tomuto issue.

**Comment by TomRehy** [comment]
![stránka produktu](https://user-images.githubusercontent.com/102223154/166416420-50eda46b-d742-4089-a95a-df3eb94cb54d.png)

**Comment by davikra11** [comment]
zaoblit jedničku a zarovnat hlavní obrázek s logem

**Comment by TomRehy** [comment]
![stránka produktu finnal](https://user-images.githubusercontent.com/102223154/166417046-8cdc77b6-32d0-4aa8-aa19-613c2df785fa.png)

**Comment by TomRehy** [comment]
Header
Fotky produktu, název produktu, cena, množství, hodnocení - možnost zvolit si barvu produktu a velikost/druh (viz. obrázek) - přidání do tašky
Informace o produktu
Komentáře od uživatelů a jejich hodnocení
Footer

**Comment by TomRehy** [comment]
@Onderko
