### ISSUE TITLE
Základní grafické rozvržení webu

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#2]
Načrtnout obecné rozložení webu, které bude následně implementováno pomocí HTML5 strukturálních tagů. Jedná se o obecný návrh pro obrazovku PC / notebooku, který bude použitý na všech stránkách webu.

Strukturální tagy HTML5: https://www.jakpsatweb.cz/html/html5-strukturni.html

Odevzdání:
1. **struktura.png** na sdíleném disku 
2. zdrojové soubory na sdíleném disku ve složce **source/structure**

**Comment by TomRehy** [comment]
![HTML structura](https://user-images.githubusercontent.com/102223154/166211277-f122cc5c-941a-4714-b726-697139c35b0
![HTML structura 2](https://user-images.githubusercontent.com/102223154/166211283-b1c9f52b-6fd1-474c-954c-f246df025072.png)
e.png)

**Comment by TomRehy** [comment]
![HTML structura](https://user-images.githubusercontent.com/102223154/166211378-1d92ba48-4f55-4a11-9c10-2dda0ada4d0d.png)

**Comment by TomRehy** [comment]
![HTML structura](https://user-images.githubusercontent.com/102223154/166213584-cf8e889a-77d1-42f1-9d15-92110987d05c.png)

**Comment by TomRehy** [comment]
![HTML structura 2](https://user-images.githubusercontent.com/102223154/166213598-14256eb3-b6ff-46a0-b0da-5c86157330ef.png)

**Comment by TomRehy** [comment]
![HTML structura](https://user-images.githubusercontent.com/102223154/166213945-8ecca8d7-24da-4f23-9af9-ee61c883dcbe.png)

**Comment by TomRehy** [comment]
![HTML structura 2](https://user-images.githubusercontent.com/102223154/166215486-270e9702-5e22-46e9-9e59-839a9d987b87.png)
![HTML structura](https://user-images.githubusercontent.com/102223154/166215491-34ac99f4-0c3b-4cef-9801-1c9c4917d95b.png)

**Comment by TomRehy** [comment]
![HTML structura 2](https://user-images.githubusercontent.com/102223154/166224803-89551906-09bd-4a2e-98e1-897a97e79e78.png)

**Comment by gabrijir11** [comment]
![navrh stranky](https://user-images.githubusercontent.com/102228437/166427689-837f8fee-7923-446e-837b-fe320ae0edc6.jpg)

**Comment by gabrijir11** [comment]
![navrh stranky 1](https://user-images.githubusercontent.com/102228437/166443096-4ed9bbec-0345-4989-84a7-1c8a28bb0d2a.jpg)
