### ISSUE TITLE
Grafický návrh - Tužky

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#23]

**Comment by gabrijir11** [comment]
![tužka black](https://user-images.githubusercontent.com/102228437/166161449-6430c580-2732-46d6-99dd-49f877e525b5.png)
![tužka bluee](https://user-images.githubusercontent.com/102228437/166161451-2e3b28d5-93d5-46e4-b6c1-45675fbce136.png)
![tužka white](https://user-images.githubusercontent.com/102228437/166161453-faed1597-44b0-4e19-8c4b-cfbce373577b.png)
![tužka yellow](https://user-images.githubusercontent.com/102228437/166161454-4294394f-daee-4bbe-a3c6-2781b98b5ca7.png)

**Comment by kubaran11** [comment]
Supr!

**Comment by gabrijir11** [comment]
uzavřít hotovo
