### ISSUE TITLE
Grafický návrh - Náramky/Potítka

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#24]

**Comment by HavelJakub** [comment]
[](url
![naramek bilej](https://user-images.githubusercontent.com/102223160/166143791-a841d854-3f36-4bd4-bd1e-c5ec4c888707.PNG)
![modry naramek](https://user-images.githubusercontent.com/102223160/166143793-91a03f3a-ffb5-4274-8ce4-3e955935f45a.PNG)
)
