### ISSUE TITLE
Grafický návrh - Triko

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#26]

**Comment by kubaran11** [comment]
Jedno triko navrhuje @davikra11 a jedno @matous-picl.

**Comment by davikra11** [comment]
![návrh trička 1](https://user-images.githubusercontent.com/102156616/166160176-853ad9c5-2add-46c0-b2cc-b7da70832664.png)

**Comment by kubaran11** [comment]
Supr, co @matous-picl ?

**Comment by matous-picl** [comment]
![Triko](https://user-images.githubusercontent.com/102512396/166198474-8a64203d-8937-4066-8de1-cde04a0a7d5d.png)

**Comment by KubaCer16** [comment]
ss

**Comment by KubaCer16** [comment]
Tričko je perfektní na všechny druhy fitness. Jeho design i pohodlí oceníte v tělocvičně i při běžném nošení! 
Heboučké, praktické a pohodlné tričko na fitness i běžné nošení. Díky bezešvému provedení, kulatému výstřihu a originálnímu designu jej budete chtít nosit každý den!
Barva: Černá/Bílá
