### ISSUE TITLE
Grafický návrh - Mikina

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#27]

**Comment by KrystofCavo23** [comment]
![mikinaSkolniBasic](https://user-images.githubusercontent.com/102223137/166189598-477ae557-34b0-42e0-897a-cae87f263afb.png)
![mikinaSkolniBasicBack](https://user-images.githubusercontent.com/102223137/166189616-c08c0b1d-a234-471f-bca2-549256582fe6.png)
