### ISSUE TITLE
Grafický návrh - Kryt na mobil

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#29]

**Comment by TomRehy** [comment]
![pouzdra pro mobil](https://user-images.githubusercontent.com/102223154/166163966-d1ccb9a7-b005-434a-95c8-181e6b5d3a0d.png)
![pouzdro pro mobil](https://user-images.githubusercontent.com/102223154/166163969-b661bcb7-227a-4fe4-b045-5607ef589ebb.png)
![pouzdro pro mobil2](https://user-images.githubusercontent.com/102223154/166163970-0f3f54b6-1c6f-49b6-b550-e5a0cb15c07a.png)
![pouzdro pro mobil3](https://user-images.githubusercontent.com/102223154/166163971-7bd7d799-5474-4d78-bf23-bf3f772d0190.png)
![pouzdro pro mobil4](https://user-images.githubusercontent.com/102223154/166163972-d8239b52-7f0e-42d9-bcf1-90007bf4745c.png)
