### ISSUE TITLE
Hlavička webu

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#3]
Připravit HTML a CSS soubory s hlavičkou webu pro PC (zatím bez logiky). Vyplnit vnitřek tagu "header". Rozvrstvit objekty tak, aby bylo možné použít libovolný počet prvků menu při načtení z databáze a aby se tomu daná hlavička byla schopná přizpůsobit.

**Prerekvizity**:

- [x] #6
- [x] #8

**Comment by kubaran11** [comment]
Hlavička webu by měla obsahovat vyhledávání a košík.

**Comment by kubaran11** [comment]
Lze se inspirovat tady: https://www.w3schools.com/howto/howto_css_dropdown.asp

**Comment by davikra11** [comment]
![Kreslicí plátno 1](https://user-images.githubusercontent.com/102156616/166225625-570a1812-2f7f-4576-962a-28c11a66ef04.png)

**Comment by Onderko** [comment]
![header1](https://user-images.githubusercontent.com/100551016/166339426-75f29e78-9049-44be-b827-ef1490c21cb3.png)

1) v headru se nachází zatím staré logo protože jsem nedostal stále upravené logo bez pozadí , proto je hlavička v bílém provedení zatím
2) košík reaguje na buttny které jsou na stránce kde se poté zopbrazí číslice s počtem věcí

**Comment by kubaran11** [comment]
Supr!

**Comment by kubaran11** [comment]
@gabrijir11 Logo bez pozadí je potřeba.

**Comment by davikra11** [comment]
![logo more bez pozadí](https://user-images.githubusercontent.com/102156616/166411051-a547b853-c145-4b3d-af66-30e98e975c5b.png)
 @Onderko tady by to mělo bejt bez toho pozadí

**Comment by Onderko** [comment]
![1navrh](https://user-images.githubusercontent.com/100551016/166540229-5428d0f3-2559-40a2-9054-809a1a52e504.png)
@kubaran11 názor?

**Comment by gabrijir11** [comment]
Hodně dobrý vrba

**Comment by Onderko** [comment]
Popřípadě javascript a 3d model mikiny
