### ISSUE TITLE
Grafický návrh - Láhev 

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#30]

**Comment by TomRehy** [comment]
![lahevŠedá](https://user-images.githubusercontent.com/102223154/166163993-e43aae7f-97da-420c-b33b-a568083924cf.png)
![lahevZelena](https://user-images.githubusercontent.com/102223154/166163995-1307cd01-0ce4-4424-bedb-4a807f83d1b8.png)
![lahevModra](https://user-images.githubusercontent.com/102223154/166163996-3a72a0a8-e0f3-4810-b563-5f90a44bdaf1.png)
![lahevRuzova](https://user-images.githubusercontent.com/102223154/166163997-5c7e1207-553e-4623-aa1c-a9a197db82d4.png)
