### ISSUE TITLE
Název webu

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#31]
Toto issue slouží k diskuzi o názvu webu s návazností na logo webu.

**Comment by gabrijir11** [comment]
Adresa nahoře SŠMGMerch.cz  
Webový title - SŠMG Merch - obchod s merchem školy SŠMG 
Název produktu - Název z databáze např. (Tričko black s logem | SŠMGMerch.cz)
Název na stránce košíku - Nákupní košík

**Comment by kubaran11** [comment]
#11 @Onderko držet strukturu na celém webu.

**Comment by gabrijir11** [comment]
Uzavřít hotovo
