### ISSUE TITLE
Grafický návrh patičky (footeru)

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#34]
Grafický návrh patičky programu.

**Comment by davikra11** [comment]
![Kreslicí plátno 1 kopie 2](https://user-images.githubusercontent.com/102156616/166226098-ee0d33b8-6d86-4f29-b23a-7827034fb4e0.png)

**Comment by kubaran11** [comment]
Tohle vypadá nedotaženě...

**Comment by kubaran11** [comment]
Hrozně jednoduchá grafika @davikra11

**Comment by davikra11** [comment]
![Kreslicí plátno 1 kopie 2](https://user-images.githubusercontent.com/102156616/166227704-d4d3c968-a49f-4789-b68f-0746cf3b242f.png)

**Comment by kubaran11** [comment]
Ještě ty sociální sítě jsou hrozný, jinak o 💯% lepší...

**Comment by kubaran11** [comment]
Ještě ty sociální sítě jsou hrozný, jinak o 💯% lepší...

**Comment by kubaran11** [comment]
@Onderko Tohle bude display: flex v display: flex načítané všechno z db, předáme na backend...

Musíš si tam přidat <div> navíc:

1. prvek display: flex 
2. prvek display: inline-flex
3. prvek display: flex (flex-direction:column)
4. prvek display:inline-flex

Rozkresli si to, jinak se ti to rozpadne, je tam potřeba vždy div navíc.

**Comment by Onderko** [comment]
![footerv2](https://user-images.githubusercontent.com/100551016/166262230-99a17083-3323-4dd4-aaad-cee304cd3e96.png)
![footerv1](https://user-images.githubusercontent.com/100551016/166262235-604e69cd-90da-4a97-86c9-38ca583f042a.png)
Dvě verze footru 1- mi přijde lepší ke stránce bude to takové vyjímečne možná ješte udělat linku pomocí br a dát jí barvu ( mezi spojte se snámi a mapou) @kubaran11 váš názor ?

**Comment by davikra11** [comment]
to druhy bude lepší podle mě, protože tam je ta mapa @Onderko

**Comment by kubaran11** [comment]
@Onderko @davikra11 Nevím, jestli je ta mapa dobrý nápad. Na jedné stránce ještě ok, ale aby byla na všech, to nevím. Celkově to chce ještě jednou graficky doladit (není to možná tím, že je tam nějaký základní font?). Mně tam ta mapa nesedí graficky, na černém brutální světlá obluda... Zato vlastní mapa, aby tam sedla designově, to by mi tam sedlo - lze dát požadavek na grafický úsek. Pokud pak někdy chcete používat mapu, tak bych pro českou klientelu použil API Map.cz, jsou lepší na českou stránku: https://api.mapy.cz/, navíc google si furt hraje se zpoplatněním...

**Comment by davikra11** [comment]
![Kreslicí plátno 1 kopie 2](https://user-images.githubusercontent.com/102156616/166413000-1d73141f-c090-4667-891d-87c3193234db.png)

**Comment by davikra11** [comment]
![Kreslicí plátno 1 kopie 2](https://user-images.githubusercontent.com/102156616/166413077-9048b34f-9ab9-4292-a3b6-beaab9ac1ad0.png)
