### ISSUE TITLE
HTML a CSS patičky programu

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#35]
HTML a CSS patičky programu dle #34 . Vzít v úvahu načítání prvků z databáze #1.

**Comment by Onderko** [comment]
<footer id="footer" class="section footer">
    <div class="container">
      <div class="footer-container">
        <div class="footer-center">
          
          <h3>ODKAZY</h3>
          <a href="#">Doprava</a>
          <a href="#">Darkové Kupony</a>
          <a href="#">Obchodní podmínky</a>
          <a href="#">Reklamační řád</a>
          <a href="#">Služby</a>
          
        </div>

        <div class="footer-center">

          <h3>O Společnosti</h3>
          <a href="#">Základní informace</a>
          <a href="#">Kariéra</a>
          <a href="#">Kontaktujte nás</a>
          <a href="#">APlikace</a>
        </div>
          
        <div class="footer-center">
          
          <h3>Najdete nás</h3>
          <div>
            <span>
              <i class="fas fa-map-marker-alt"></i>
            </span>
            Školní 145, 282 01 Český Brod CZ
          </div>
          <div>
            <span>
              <i class="far fa-envelope"></i>
            </span>
            info@sosceskybrod.cz
          </div>
          <div>
            <span>
              <i class="fas fa-phone"></i>
            </span>
            763048374065
          </div>
      

          <div class="payment-methods">
            <img src="./images/payment.png" alt="">
          </div>
          
        </div>
      </div>
    </div>
    </div>
  </footer>

**Comment by kubaran11** [comment]
Budu potřebovat vidět CSS, aby tam nebyly nějaké věci, které by nás později limitovaly. Prvky jednotlivých částí umístit do DB #3.

**Comment by kubaran11** [comment]
@KubaCer16 Bude potřeba přidat tyto stránky do #33.

**Comment by Onderko** [comment]
/* FOOTER */

.footer {
  background-color: var(--black);
  padding: 6rem 1rem;
  line-height: 3rem;
}

.footer-center span {
  margin-right: 1rem;
}

.footer-container {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  color: var(--white);
}

.footer-center a:link,
.footer-center a:visited {
  display: flex;
  color: #f1f1f1;
  font-size: 1.4rem;
  transition: 0.6s;
}

.footer-center a:hover {
  color: var(--primary);
}

.footer-center div {
  color: #f1f1f1;
  font-size: 1.4rem;
}

.footer-center h3 {
  font-size: 1.8rem;
  font-weight: 400;
  margin-bottom: 1rem;
}

.footer .payment-methods {
  margin-top: 2rem;
}
