### ISSUE TITLE
Obsah košíku

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#37]
Připravit, jaké všechny informace by měly být v košíku.

**Comment by KubaCer16** [comment]
•	Název produktu
•	Počet produktů
•	Počet kusů skladem
•	Cena za kus
•	Cena celkem bez DPH/s DPH
•	Slevové kódy
![obrazek](https://user-images.githubusercontent.com/102223032/166225666-c983588f-99e3-474e-aa44-7663e4cdbb7b.png)

**Comment by KubaCer16** [comment]
Doprava a platba
•	Vyberte dopravu
o	Osobní odběr cena a datum příjezdu 
•	Vyberte platbu
o	Kartou online
o	Google Pay
o	Při vyzvednutí
o	Česká spořitelna
o	Komerční banka 
o	Fio bank
o	ČSOB  
o	UniCredit Bank

**Comment by KubaCer16** [comment]
3.	Dodací údaje 
•	Kontaktní údaje 
o	E-mail 
o	Telefon 
o	Jméno 
o	Příjmení 
•	Dokončit a zaplatit 
•	Souhrn nákupu

**Comment by KubaCer16** [comment]
4.	DĚKUJEME ZA NÁKUP

**Comment by KubaCer16** [comment]
[Košík.pdf](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI/files/8602580/Kosik.pdf)
[Košík.docx](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI/files/8602581/Kosik.docx)

**Comment by davikra11** [comment]
![návrh košíku](https://user-images.githubusercontent.com/102156616/166425512-3d13a8ce-0fff-4477-8e3d-66c3df08861e.png)
![návrh adresa](https://user-images.githubusercontent.com/102156616/166425521-7ff4f5a2-697c-4ae2-8c87-b3f622e4c8cd.png)
![návrh platby](https://user-images.githubusercontent.com/102156616/166425529-11e4c29e-c894-4631-9a1e-bf3bd702fdea.png)
