### ISSUE TITLE
Grafický návrh - Ponožky

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#39]

**Comment by matysko11** [comment]
![Merch ponožky černé logo](https://user-images.githubusercontent.com/102223073/166189962-014aa240-e026-40d5-a195-7f3d93210a15.jpg)
![Merch ponožky modré logo](https://user-images.githubusercontent.com/102223073/166189965-78bd24fa-43a6-4c1c-990d-ea53d00a5ebf.jpg)

**Comment by matysko11** [comment]
![ponožky](https://user-images.githubusercontent.com/102223073/166217130-10e0ddd3-a2ff-4137-9784-0cf186ab5fe1.png)
![ponožky balckie](https://user-images.githubusercontent.com/102223073/166217140-c1bd8fd5-745b-4703-96da-f93083c4efd2.png)
