### ISSUE TITLE
Ikonka pro vyhledání kategorie a ikonka pro vyhledání produktu

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#40]
musí vyhledávat i kategorie

_Originally posted by @HavelJakub in https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI/issues/14#issuecomment-1114654762_

Při vyhledávání produktu potřebujeme indexovat kategorie a produkty, potřebujeme ikonku.

**Comment by kubaran11** [comment]
Nahrát do icons/.. na sdíleném disku.

**Comment by KrystofCavo23** [comment]
![searchbarcategorys](https://user-images.githubusercontent.com/102223137/166225258-8c54638e-0e33-4fae-9c57-0824b461afee.png)
![search](https://user-images.githubusercontent.com/102223137/166225267-b3144d7e-f806-4a44-b5be-8b68df81c31c.png)

**Comment by KrystofCavo23** [comment]
![searchbarcategorysYellow](https://user-images.githubusercontent.com/102223137/166441235-ce022a42-6219-46e2-bea6-75f5b0c92a79.png)
