### ISSUE TITLE
LOGO STRÁNKY + MINI IKONKA STRÁNKY

### ISSUE THREAD

**Issue by gabrijir11** [Stredni-skola-managementu-a-grafiky/UP3AI#42]
![logo reworked](https://user-images.githubusercontent.com/102228437/166225382-178f11ff-9cc3-4bb0-9052-0f46374870b4.png)

**Comment by gabrijir11** [comment]
![compass-icon-13549](https://user-images.githubusercontent.com/102228437/166225735-32a837ac-b576-45a4-8c1c-5db3ca707a98.png)

**Comment by kubaran11** [comment]
Duplicate of #32
