### ISSUE TITLE
Návrh stránky pro kategorie

### ISSUE THREAD

**Issue by davikra11** [Stredni-skola-managementu-a-grafiky/UP3AI#47]

**Comment by TomRehy** [comment]
![návrh kategorii doplňky](https://user-images.githubusercontent.com/102223154/166438621-067dba83-190b-4ef3-826d-514bd2ad5901.png)

**Comment by davikra11** [comment]
![návrh kategorii](https://user-images.githubusercontent.com/102156616/166439914-c3d53a7e-04bc-4eab-aec8-2fa20f33c196.png)
