### ISSUE TITLE
Klíčenka SŠMG

### ISSUE THREAD

**Issue by gabrijir11** [Stredni-skola-managementu-a-grafiky/UP3AI#49]

**Comment by KrystofCavo23** [comment]
![klicenka black3](https://user-images.githubusercontent.com/102223137/166650185-2080f057-8228-4ba7-87b6-6feeb216f028.png)
![klicenka green1](https://user-images.githubusercontent.com/102223137/166650189-e8d82d77-b534-48d7-8d55-893e8396152b.png)
![klicenka green2](https://user-images.githubusercontent.com/102223137/166650190-1609f0c1-2fe0-4f25-83e3-ecb1509d6314.png)
![klicenka ligtblue1](https://user-images.githubusercontent.com/102223137/166650198-b12ee998-8376-42db-9139-e12381a4ef2d.png)
![klicenka ligtblue2](https://user-images.githubusercontent.com/102223137/166650202-7a489e6d-92c7-493b-902e-9afc1b3da737.png)
![klicenka ligtblue3](https://user-images.githubusercontent.com/102223137/166650208-513bf1dc-84ca-4161-ab0a-a5bbca903f48.png)
![klicenka pink1](https://user-images.githubusercontent.com/102223137/166650217-174c5474-857e-4553-bfe1-379404989738.png)
![klicenka pink2](https://user-images.githubusercontent.com/102223137/166650219-4cca7a24-6f02-432e-8de3-6bbff480994a.png)
![klicenka pink3](https://user-images.githubusercontent.com/102223137/166650223-da4828e7-3b70-4de9-a708-863299292500.png)
![klicenka pink4](https://user-images.githubusercontent.com/102223137/166650229-be8d0c52-3f4d-4dea-bc00-bdef10abd3f3.png)
![klicenka pink5](https://user-images.githubusercontent.com/102223137/166650234-50f47069-d80b-4a3a-9500-00cb85528e34.png)
![klicenka pink6](https://user-images.githubusercontent.com/102223137/166650238-ef59e9dd-d227-4955-99f0-43063cc791ea.png)
![klicenka white 4](https://user-images.githubusercontent.com/102223137/166650244-bb33c697-0c00-4c03-97d2-4cd8dbb9b0aa.png)
![klicenka white1](https://user-images.githubusercontent.com/102223137/166650249-0c9dcfda-69f1-45a4-8970-509d15b63c92.png)
![klicenka white2](https://user-images.githubusercontent.com/102223137/166650253-c06d83c5-0f53-427c-8f5f-caecacde169e.png)
![klicenka white3](https://user-images.githubusercontent.com/102223137/166650257-e6925ff5-86aa-4d12-b62e-c9de6c94b897.png)
![klicenka black1](https://user-images.githubusercontent.com/102223137/166650265-6347823b-a771-457f-a191-31443a52c24b.png)
![klicenka black2](https://user-images.githubusercontent.com/102223137/166650273-b65feda3-e506-4049-a1ad-2996b311d959.png)
