### ISSUE TITLE
Algoritmus pro automatické načítání prvků menu z databáze

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#5]
Je nutné připravit algoritmus, který umožní dynamické fungování úvodního menu z databáze při libovolném počtu prvků. Předtím je nutné vyřešit #3 a #4. Při úpravě bude možná potřeba zasáhnout do #1.

**Comment by kubaran11** [comment]
`<?php 

function getMenu($prefix, $startIndex, $stopIndex)
{
    /**
     * Method returns HTML code for top navigation from startIndex to stopIndex
     * 
     * @param String $prefix        Level of directory (Values like "" or "../" or "../../") 
     * @param integer $startIndex   Database parametr idNavigation start index include this value
     * @param integer $stopIndex    Database parametr idNavigation stop index include this value
     * 
     * @author Jakub Ransdorf <jakub1237@centrum.cz>
     * @return $menuHTML 
     */

    $conn = $GLOBALS['conn'];

    $menuHTML = "";
    $mysql = "SELECT COUNT(*) FROM Menu WHERE idNavigation BETWEEN ? AND ?";
    $stmt = $conn ->prepare($mysql);
    $stmt -> bind_param("ii", $startIndex, $stopIndex);
    $stmt -> execute();
    $stmt -> store_result();
    $stmt -> bind_result($count);
    $stmt ->fetch();



    for ($i = $startIndex; $i<$startIndex+($count*10); $i+=10)
    {   
        $mysql = "SELECT idNavigation, description, link, target FROM Menu WHERE idNavigation = ? AND active='1'";
        $stmt = $conn->prepare($mysql);
        $stmt -> bind_param("i", $i);
        $stmt -> execute();
        $stmt -> store_result();
        $stmt -> bind_result($id, $nazev, $odkaz, $target);
        
        while($stmt ->fetch())		
        {
            $menuHTML .= "<li id=nav$id><a target='_$target' href='$prefix$odkaz'>$nazev</a>";
        }

        $underTest = $id*10;
        $upperTest = $id*10+99;
        $sql = "SELECT description,link,target,idNavigation  FROM Menu WHERE idNavigation BETWEEN ? AND ? AND active='1'";
        $stmt = $conn -> prepare($sql);
        $stmt-> bind_param("ss",$underTest, $upperTest);
        $stmt -> execute();
        $stmt -> store_result();
        $stmt -> bind_result($nazev, $odkaz, $target,$id);
        $isUlDid = False;

        while ($stmt -> fetch())
        {

            if($isUlDid == False)
            {
                $menuHTML .= "<ul class='dropdown-box'>";
                $isUlDid = True;
            }
            
            $menuHTML .= "<li id='nav$id'><a href='$prefix$odkaz' target='_$target'>$nazev</a>";
            $menuHTML .= "</li>";

        }
        if($isUlDid)
        {
            $menuHTML .= "</ul>";
        }
        $menuHTML .= "</li>";
    }

    return $menuHTML;
}



function getFooterMenu($prefix, $startIndex, $stopIndex)
{
    /**
     * Method returns HTML code for top navigation from startIndex to stopIndex
     * 
     * @param String $prefix        Level of directory (Values like "" or "../" or "../../") 
     * @param integer $startIndex   Database parametr idNavigation start index include this value
     * @param integer $stopIndex    Database parametr idNavigation stop index include this value
     * 
     * @author Jakub Ransdorf <jakub1237@centrum.cz>
     * @return $menuHTML 
     */

    $conn = $GLOBALS['conn'];

    $menuHTML = "";
    $mysql = "SELECT COUNT(*) FROM Menu WHERE idNavigation BETWEEN ? AND ?";
    $stmt = $conn ->prepare($mysql);
    $stmt -> bind_param("ii", $startIndex, $stopIndex);
    $stmt -> execute();
    $stmt -> store_result();
    $stmt -> bind_result($count);
    $stmt ->fetch();



    for ($i = $startIndex; $i<$startIndex+($count*10); $i+=10)
    {   
        $mysql = "SELECT idNavigation, description, link, target FROM Menu WHERE idNavigation = ? AND active='1'";
        $stmt = $conn->prepare($mysql);
        $stmt -> bind_param("i", $i);
        $stmt -> execute();
        $stmt -> store_result();
        $stmt -> bind_result($id, $nazev, $odkaz, $target);
        
        while($stmt ->fetch())		
        {
            $menuHTML .= "<div class='container'><li class=outside id=nav$id><a target='_$target' href='$prefix$odkaz'>$nazev</a>";
        }

        $underTest = $id*10;
        $upperTest = $id*10+99;
        $sql = "SELECT description,link,target,idNavigation  FROM Menu WHERE idNavigation BETWEEN ? AND ? AND active='1'";
        $stmt = $conn -> prepare($sql);
        $stmt-> bind_param("ss",$underTest, $upperTest);
        $stmt -> execute();
        $stmt -> store_result();
        $stmt -> bind_result($nazev, $odkaz, $target,$id);
        $isUlDid = False;

        while ($stmt -> fetch())
        {

            if($isUlDid == False)
            {
                $menuHTML .= "<ul class='dropdown-box'>";
                $isUlDid = True;
            }
            
            $menuHTML .= "<li class=inside id='nav$id'><a href='$prefix$odkaz' target='_$target'>$nazev</a>";
            $menuHTML .= "</li>";

        }
        if($isUlDid)
        {
            $menuHTML .= "</ul>";
        }
        //Prasárna UPRAVIT!!
        if(substr($menuHTML,strlen($menuHTML)-11) != "</li></div>")
        {
            $menuHTML .= "</li></div>";
        }
    }

    return $menuHTML;
}



?>`

**Comment by HavelJakub** [comment]
`<?php
function getCategory($name)
{
    $conn = $GLOBALS['conn'];

    $mysql = "SELECT name,image_url From Category;
    $stmt = $conn ->prepare($mysql);
    $stmt -> bind_param("s", $name);
    $stmt -> execute();
    $stmt -> store_result();
    $stmt -> bind_result($name, $image_url);
    $stmt ->fetch();
    $stmt->close();

"    $categoryArray = array("name"=>$name, "image_url"=>$image_url );

    return $categoryArray;

function getAllCategories()
{
    $conn = $GLOBALS['conn'];

    $categoryArray = array();
    $mysql = "SELECT id FROM Category";
    $stmt = $conn ->prepare($mysql);
    $stmt -> execute();
    $stmt -> store_result();
    $stmt -> bind_result($id);
    while ($stmt ->fetch())
    {
        array_push($categoryArray, $id);
    }
    $stmt->close();

    return $categoryArray;
}



?>`

**Comment by HavelJakub** [comment]
<?php
$servername = "shop";
$username = "shop";
$password = "5itsE3ay8Qh8XlVR";
$dbname = "shop";

?>

**Comment by HavelJakub** [comment]
<?php
$servername = "shop";
$username = "shop";
$password = "5itsE3ay8Qh8XlVR";
$dbname = "shop";

?>

**Comment by HavelJakub** [comment]
`<?php
$servername = "shop";
$username = "shop";
$password = "5itsE3ay8Qh8XlVR";
$dbname = "shop";

?>`

**Comment by HavelJakub** [comment]
[getCategory.txt](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI/files/8609285/getCategory.txt)
[conn.txt](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI/files/8609286/conn.txt)
