### ISSUE TITLE
Grafický návrh ikony nákupního košíku

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#6]
Připravit grafický návrh speciální malé ikonky nákupního košíku jako symbolu, který se bude prolínat celým webem.

Výsledná ikona je umístěna:

   1. Umístění: "**icons/basket.png**" s průhledným pozadím na sdíleném disku (rozměry 50 x 50 px, velikost redukována pro web)

**Comment by gabrijir11** [comment]
![bag 2](https://user-images.githubusercontent.com/102228437/166206097-401dd144-15bf-4503-bfdd-9b2b4c82973b.png)
![bag3](https://user-images.githubusercontent.com/102228437/166206099-0d11e79b-9367-4b37-9851-6b66c4e5dc53.png)

**Comment by gabrijir11** [comment]
uzavřít hotovo

**Comment by kubaran11** [comment]
#11 Brát v úvahu absolutní pozicování hodnot v košíku pomocí CSS a JS.

**Comment by gabrijir11** [comment]
ikona stránky
![compass-icon-13549](https://user-images.githubusercontent.com/102228437/166220741-341e588e-60ea-4c20-8764-9a13ea0554b2.png)
