### ISSUE TITLE
PENĚŽENKY SŠMG

### ISSUE THREAD

**Issue by gabrijir11** [Stredni-skola-managementu-a-grafiky/UP3AI#61]

**Comment by Springpeace2** [comment]
![cyan wallet white logo ssmg](https://user-images.githubusercontent.com/102223748/166665492-9bc3e47d-416c-468d-b6e2-b7e1febbd175.png)

**Comment by Springpeace2** [comment]
![lime wallet logo ssmg merch classic](https://user-images.githubusercontent.com/102223748/166665549-12ca86ad-65e6-4e93-9eec-5af40d96586e.png)
![black wallet black logo ssmg](https://user-images.githubusercontent.com/102223748/166665553-429de2c9-e7bd-4791-a93b-a579a77024df.png)
![black wallet white logo ssmg](https://user-images.githubusercontent.com/102223748/166665556-d13d810e-9884-4edc-8315-3404863666ab.png)
![black wallet logo ssmg merch white_](https://user-images.githubusercontent.com/102223748/166665558-6bf0de16-3eca-46bf-a23b-d54953bbad21.png)
![black wallet black logo ssmg merch calssic_](https://user-images.githubusercontent.com/102223748/166665561-1494847a-26a9-4872-b077-e6c4a6aeca06.png)
![lime wallet white logo ssmg](https://user-images.githubusercontent.com/102223748/166665564-afce4d8e-5459-4a02-a4c5-03d1f06b399d.png)
![lime wallet white logo ssmg merch classic](https://user-images.githubusercontent.com/102223748/166665565-98d80a10-5184-4866-b2ee-6b11bb31ee24.png)
![lime wallet balck logo ssmg](https://user-images.githubusercontent.com/102223748/166665568-b580ac03-dc7d-403f-91e8-39284b4e77cc.png)
![blue wallet ssmg black logo](https://user-images.githubusercontent.com/102223748/166665570-20d3d22e-3c1e-4ef6-ac9c-e32db9e2a9d7.png)
![blue wallet ssmg logo](https://user-images.githubusercontent.com/102223748/166665571-9851f115-c134-41d8-9a00-c93384fe0b07.png)
![blue wallet white logo ssmg merch](https://user-images.githubusercontent.com/102223748/166665572-073326ae-035b-43ee-af7c-ba4f3357fa7f.png)
![blue wallet white logo](https://user-images.githubusercontent.com/102223748/166665575-f519b899-d3ed-47d8-bc6b-bf803d5d92ff.png)
![cyan wallet black logo ssmg](https://user-images.githubusercontent.com/102223748/166665578-99ff709e-a556-4c20-a355-7cababe6a05d.png)
![cyan wallet logo ssmg classic](https://user-images.githubusercontent.com/102223748/166665580-4da2376c-f0d9-40a6-a6ef-77f9985ea361.png)
![cyan wallet white logo ssmg merch](https://user-images.githubusercontent.com/102223748/166665582-2cc64b79-794f-41da-b311-764051cbe766.png)
![cyan wallet white logo ssmg](https://user-images.githubusercontent.com/102223748/166665583-99814ab5-6de1-4eff-b2c1-da06dda6fe99.png)
![dark blue wallet black logo](https://user-images.githubusercontent.com/102223748/166665587-f4fa6016-c4de-4cc9-8eff-6efd31d152f0.png)
![dark blue wallet logo merch](https://user-images.githubusercontent.com/102223748/166665588-0ff795e1-79d2-4b65-98f4-f76be4151d76.png)
![dark blue wallet logo white](https://user-images.githubusercontent.com/102223748/166665590-64ceea00-85d9-4a6a-9bb1-3bc8a1680153.png)
![dark blue wallet white logo merch](https://user-images.githubusercontent.com/102223748/166665593-8838483f-14e0-464a-8cd2-cec397a9066a.png)
![pink wallet white logo ssmg](https://user-images.githubusercontent.com/102223748/166665596-24c29f0e-f6fa-4d78-8edf-cdcba52b9f09.png)
![pink wallet logo ssmg merch classic](https://user-images.githubusercontent.com/102223748/166665597-e92b78a9-079b-4420-80e5-af30efcd2048.png)
![pink wallet black logo ssmg](https://user-images.githubusercontent.com/102223748/166665600-60797d4d-cebf-4c93-8c98-2a68e51ddc5b.png)
![pink wallet white logo ssmg merch](https://user-images.githubusercontent.com/102223748/166665602-f27952f4-363a-4905-aaae-b08ba829755b.png)
