### ISSUE TITLE
Návrh O nás HTML CSS

### ISSUE THREAD

**Issue by KrystofCavo23** [Stredni-skola-managementu-a-grafiky/UP3AI#65]
![O nás](https://user-images.githubusercontent.com/102223137/166885905-b155d8b2-7a84-485c-986f-848672cedc18.png)

**Comment by KrystofCavo23** [comment]
text at se to pak nemusi prepisovat: SŠMG MERCH začal vznikat 2.5. 2022. Podílelo se na něm spoustu lidí(Jakub Ransdorf, David Kramář, Matěj Skořepa, Jirka Gabriel, Tomáš Řehák, Jakub Havel, Jaromír Štekl, Kryštof Kuchař, Matouš Pícl, Jakub Černý a Ondřej Vrbata) s cílem vytvořit merch a E-Shop školy SŠMG, pro podporu školy, a aby každý mohl ukázát jak moc miluje SŠMG! Vše vyrábíme v České Republice z prémiových materiálů. I tak se snažíme ceny udržet v normě. 20% zisku posílámé na různé charity, a na podporu dětem. Také se snažíme podporovat školství v zemích třetího světa. Na našem E-Shopu najdete desítky produktů v každé kategorii s různými styly, každý by si měl přijít na své :). Naše škola sídlí v Školní 145, 282 01 Český Brod, je zde již 134 let, máme 149 žáků a 17 učitelů. A také nesmíme zapomenout na naše sponzory jako je PHtonery, Český Brod, Středočeský Kraj, MŠMT, cermat. Viz. sosceskybrod.cz. Doufáme a věříme, že oceníte naší práci, podpoříte nás i naší školu a nakoupíte na náš prémiový merch.

**Comment by KrystofCavo23** [comment]
HTML a CSS, je to jen ten blok


HTML:
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>O nás</title>
    <link rel="stylesheet" href="onas.css">
</head>
<body>
    <div class="about">
        <div class="inner-section">
            <h1>O SŠMG Merch:</h1>
            <p class="text">SŠMG MERCH začal vznikat 2.5. 2022. Podílelo se na něm spoustu lidí(Jakub Ransdorf, David Kramář, Matěj Skořepa, Jirka Gabriel, Tomáš Řehák, Jakub Havel, Jaromír Štekl, Kryštof Kuchař, Matouš Pícl, Jakub Černý a Ondřej Vrbata) s cílem vytvořit merch a E-Shop školy SŠMG, pro podporu školy, a aby každý mohl ukázát jak moc miluje SŠMG! Vše vyrábíme v České Republice z prémiových materiálů. I tak se snažíme ceny udržet v normě. 20% zisku posílámé na různé charity, a na podporu dětem. Také se snažíme podporovat školství v zemích třetího světa. Na našem E-Shopu najdete desítky produktů v každé kategorii s různými styly, každý by si měl přijít na své :). Naše škola sídlí v Školní 145, 282 01 Český Brod, je zde již 134 let, máme 149 žáků a 17 učitelů. A také nesmíme zapomenout na naše sponzory jako je PHtonery, Český Brod, Středočeský Kraj, MŠMT, cermat. Viz. sosceskybrod.cz. Doufáme a věříme, že oceníte naší práci, podpoříte nás i naší školu a nakoupíte na náš prémiový merch.<img src="skola.jpg" class="skola"> </p>
            
        </div>
    </div>
</body>
</html>

CSS:

*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    
}
body{
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;

}
.about{
    
}
.inner-section{
    color: white;
    margin: 30%;
    background-color:rgba(37, 37, 37, 0.63);
    border-radius: 25px;
    padding: 20px;
    width: 2000px;
    height: 2750px;
    
}
.inner-section h1{
    font-size: 120px;

}
.inner-section p{
    font-size: 60px;
    
}
.skola {
    width: 85%;
    margin-top: 20%;
    margin-left: 7%;

}

**Comment by KrystofCavo23** [comment]
![Snímek obrazovky (3)](https://user-images.githubusercontent.com/102223137/166906156-465ac5ae-ea6a-4ef1-a06d-03dce6249441.png)
pak na tom pozadí to vypadá takhle

**Comment by matysko11** [comment]
[indexx.txt](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI/files/8631088/indexx.txt)
[csss.txt](https://github.com/Stredni-skola-managementu-a-grafiky/UP3AI/files/8631089/csss.txt)
