### ISSUE TITLE
Grafický návrh ikony vyhledávače

### ISSUE THREAD

**Issue by kubaran11** [Stredni-skola-managementu-a-grafiky/UP3AI#7]
Připravit grafický návrh speciální malé ikonky pro vyhledání prvku jako symbolu, který se bude prolínat celým webem.

Výsledná ikona je umístěna:

   1. Umístění: "**icons/search.png**" s průhledným pozadím na sdíleném disku (rozměry 50 x 50 px, velikost redukována pro web)

**Comment by KrystofCavo23** [comment]
![search](https://user-images.githubusercontent.com/102223137/166206349-d089c99f-1258-40d3-af5d-4473afbb2687.png)

**Comment by KrystofCavo23** [comment]
![search](https://user-images.githubusercontent.com/102223137/166207494-a391fb99-3476-4b00-992b-055833eccc7d.png)

**Comment by kubaran11** [comment]
Má ta ikona průhledné pozadí i na webu a máme jí ve vektorové grafice? @KrystofCavo23
